### ISSUE TITLE
Please make english version.

### ISSUE THREAD

**Issue by Jakeverse** [huuhghhgyg/Chamberlain_UWP#14]
I have been waiting so long for this kind of to do list app. At last you have done it. please make english version so we everyone can use this great app. :)

**Comment by huuhghhgyg** [comment]
I would like to 🤣
Give me some time to learn how to add multilingual support to it

**Comment by huuhghhgyg** [comment]
Hi, @Jakeverse, I want to let you know that I have released a new version v1.0.9 of the software, and it now includes English language support. You can now use the program in English without any issues.

Thank you for bringing up this request. I believe this update will greatly enhance the usability of the software for English-speaking users.

If you have any further questions or need any assistance, please feel free to reach out 😉

**Comment by Jakeverse** [comment]
Thank you so much for releasing english version installer today. It's so early! I have checked your apps progress everyday and waited for english translation. Now I have got chance to use this beautiful app. You're so hardworking developer, I hope this app will be the best to-do app in the future. You can release it in microsoft store, this way people will know about this great app and can use it. 😊

Now I can use Chamberlain peacefully in my personal workspace, it gives me a refreshing vibe. 😌 I'm so lucky to got a app that I always wanted. Simple, Minimal and Beautiful app. Thank you very much.

**Comment by huuhghhgyg** [comment]
It was not until today that I found out that the language switching function of the lastest uploaded v1.0.9 did not work. It may be due to a packaging problem. I don’t know if you have encountered the same problem. I repackaged and uploaded a new version today. If you have any questions, feel free to raise Issue on GitHub. I wish you a happy life 😉

**Comment by Jakeverse** [comment]
I don't encountered this bug, simply opened with english language by default. Thanks for letting me know and still improving english translation. I'm now feeling so alive using Chamberlain. 😊
